//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeEDU.FreeEDU_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FreeEDU_Service.IFreeEDU_Service")]
    public interface IFreeEDU_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreeEDU_Service/GetAccount", ReplyAction="http://tempuri.org/IFreeEDU_Service/GetAccountResponse")]
        System.ValueTuple<string, string, string> GetAccount(string email, string hashPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreeEDU_Service/GetAccount", ReplyAction="http://tempuri.org/IFreeEDU_Service/GetAccountResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<string, string, string>> GetAccountAsync(string email, string hashPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreeEDU_Service/CreateAcount", ReplyAction="http://tempuri.org/IFreeEDU_Service/CreateAcountResponse")]
        System.ValueTuple<string, string> CreateAcount(string login, string Email, string hashPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreeEDU_Service/CreateAcount", ReplyAction="http://tempuri.org/IFreeEDU_Service/CreateAcountResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<string, string>> CreateAcountAsync(string login, string Email, string hashPass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFreeEDU_ServiceChannel : FreeEDU.FreeEDU_Service.IFreeEDU_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FreeEDU_ServiceClient : System.ServiceModel.ClientBase<FreeEDU.FreeEDU_Service.IFreeEDU_Service>, FreeEDU.FreeEDU_Service.IFreeEDU_Service {
        
        public FreeEDU_ServiceClient() {
        }
        
        public FreeEDU_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FreeEDU_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FreeEDU_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FreeEDU_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ValueTuple<string, string, string> GetAccount(string email, string hashPass) {
            return base.Channel.GetAccount(email, hashPass);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<string, string, string>> GetAccountAsync(string email, string hashPass) {
            return base.Channel.GetAccountAsync(email, hashPass);
        }
        
        public System.ValueTuple<string, string> CreateAcount(string login, string Email, string hashPass) {
            return base.Channel.CreateAcount(login, Email, hashPass);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<string, string>> CreateAcountAsync(string login, string Email, string hashPass) {
            return base.Channel.CreateAcountAsync(login, Email, hashPass);
        }
    }
}
